name: Using hello world
on: [push]

jobs:
  hello_world_job:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macOS-latest, windows-latest]
    name: A job to say hello
    steps:
      # To use this repository's private action, you must check out the repository
      - name: Checkout
        uses: actions/checkout@v2
      - name: Hello world action step
        uses: ULL-MII-SYTWS-2122/hello-js-action-nicolas-hernandez-gonzalez-alu0100898293@v1
        id: hello
        with:
          who-to-greet: 'Sistemas y Tecnología Web: Servidor at ULL'
      # Use the output from the `hello` step
      - name: Get the output time
        run: echo "The time was ${{ steps.hello.outputs.time }}"